### Listar todos os livros
GET http://localhost:8080/books
Accept: application/json


### Adicionar um novo livro
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "genre": "Software Engineering"
}

### Listar 1 livro especifico
GET http://localhost:8080/books/2
Accept: application/json

### Atualizar um livro existente
GET http://localhost:8080/books/2
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "genre": "Software Development"
}

### Deletar um livro
DELETE http://localhost:8080/books/1

### Simular leitura de múltiplos livros via POST com JSON
POST http://localhost:8080/simulate-reading
Content-Type: application/json

{
  "book_ids": [1, 2, 3]
}